server {
    listen 80;

    # 프론트엔드 화면 서빙
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 프론트 상대경로(/books, /reviews) 요청을 K8s 백엔드 서비스로 전달
    location /books {
        proxy_pass http://backend-service:8080/books;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /reviews {
        proxy_pass http://backend-service:8080/reviews;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 로그인/회원가입(JWT 발급)
    location /auth {
        proxy_pass http://backend-service:8080/auth;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 관리자 기능
    location /admin {
        proxy_pass http://backend-service:8080/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}